<a href="https://colab.research.google.com/github/Desmond-dev12/Supermarket_sales_ipynb/blob/main/Trial_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving supermarket_messy.csv to supermarket_messy.csv

In [2]:
import pandas as pd
df = pd.read_csv("supermarket_messy.csv")

print('shape', df.shape)
df.head(5)

shape (205, 16)

,Invoice ID,BRANCH,City,customer type,Gender,Product Line,Unit Price (GHS),Quantity,Tax 5%,Total,Date,Payment,cogs,gross margin percentage,gross income,Rating
0,658-21-7912,C,Naypyitaw,Member,Male,Sports and travel,34.75 GHS,4.0,6.9500,145.95,3/24/2019,Cash,139.00,4.761905,6.9500,4.8
1,818-79-7873,A,Yangon,Member,Male,Electronic accessories,30.94 GHS,10.0,15.4700,NaN,"March 21, 2019",Cash,309.40,4.761905,15.4700,4.2
2,320-53-2674,A,Yangon,NaN,FEMALE,Food and beverages,78.29 GHS,3.0,11.7435,246.61,2/5/2019,Ewallet,234.87,4.761905,11.7435,8.2
3,649-25-7201,A,Yangon,Normal,Male,Fashion accessories,86.27 GHS,10.0,43.1350,905.83,"March 15, 2019",Cash,862.70,4.761905,43.1350,5.6
4,975-39-2654,A,Yangon,Normal,NaN,Home and lifestyle,27.31 GHS,2.0,2.7310,57.35,"February 3, 2019",Cash,54.62,4.761905,2.7310,4.3

In [3]:
df.tail()

,Invoice ID,BRANCH,City,customer type,Gender,Product Line,Unit Price (GHS),Quantity,Tax 5%,Total,Date,Payment,cogs,gross margin percentage,gross income,Rating
200,695-57-8753,C,Naypyitaw,Normal,FEMALE,Food and beverages,18.37 GHS,4.0,3.6740,77.15,2/22/2019,Cash,73.48,4.761905,3.6740,NaN
201,744-83-4185,A,Yangon,Member,Male,Food and beverages,14.16 GHS,8.0,5.6640,118.94,2/14/2019,Cash,113.28,4.761905,5.6640,7.7
202,846-50-8149,B,Mandalay,Member,Male,Fashion accessories,26.07 GHS,5.0,6.5175,136.87,2/12/2019,Credit card,130.35,4.761905,6.5175,4.2
203,643-47-8433,B,Mandalay,Member,Male,Electronic accessories,34.75 GHS,10.0,17.3750,364.88,2/20/2019,Ewallet,347.50,4.761905,17.3750,7.3
204,179-82-2838,NaN,Mandalay,Member,Male,Sports and travel,77.93 GHS,2.0,7.7930,NaN,"March 12, 2019",Credit card,155.86,4.761905,7.7930,7.2

In [4]:
df.columns.tolist()

['Invoice ID ',
 'BRANCH',
 'City',
 'customer type',
 'Gender  ',
 'Product Line',
 'Unit Price (GHS)',
 'Quantity',
 'Tax 5%',
 'Total',
 'Date',
 'Payment',
 'cogs',
 'gross margin percentage',
 'gross income',
 'Rating']

In [5]:
print(repr(df.columns))

Index(['Invoice ID ', 'BRANCH', 'City', 'customer type', 'Gender  ',
       'Product Line', 'Unit Price (GHS)', 'Quantity', 'Tax 5%', 'Total',
       'Date', 'Payment', 'cogs', 'gross margin percentage', 'gross income',
       'Rating'],
      dtype='object')

In [6]:
df.columns = df.columns.str.lower().str.strip().str.replace(" ", "_")

print(df.columns)

Index(['invoice_id', 'branch', 'city', 'customer_type', 'gender',
       'product_line', 'unit_price_(ghs)', 'quantity', 'tax_5%', 'total',
       'date', 'payment', 'cogs', 'gross_margin_percentage', 'gross_income',
       'rating'],
      dtype='object')

In [7]:
#renaming columns names
df = df.rename(columns={"gross_margin_percentage": "gross_margin",
                       "unit_price_(ghs)": "unit_price",
                       "tax_5%": "tax"})
print(df.columns)

Index(['invoice_id', 'branch', 'city', 'customer_type', 'gender',
       'product_line', 'unit_price', 'quantity', 'tax', 'total', 'date',
       'payment', 'cogs', 'gross_margin', 'gross_income', 'rating'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   invoice_id     205 non-null    object
 1   branch         186 non-null    object
 2   city           205 non-null    object
 3   customer_type  189 non-null    object
 4   gender         192 non-null    object
 5   product_line   205 non-null    object
 6   unit_price     205 non-null    object
 7   quantity       205 non-null    float64
 8   tax            205 non-null    float64
 9   total          184 non-null    float64
 10  date           205 non-null    object
 11  payment        205 non-null    object
 12  cogs           205 non-null    float64
 13  gross_margin   205 non-null    float64
 14  gross_income   205 non-null    float64
 15  rating         188 non-null    float64
dtypes: float64(7), object(9)
memory usage: 25.8+ KB

In [9]:
df.head()

,invoice_id,branch,city,customer_type,gender,product_line,unit_price,quantity,tax,total,date,payment,cogs,gross_margin,gross_income,rating
0,658-21-7912,C,Naypyitaw,Member,Male,Sports and travel,34.75 GHS,4.0,6.9500,145.95,3/24/2019,Cash,139.00,4.761905,6.9500,4.8
1,818-79-7873,A,Yangon,Member,Male,Electronic accessories,30.94 GHS,10.0,15.4700,NaN,"March 21, 2019",Cash,309.40,4.761905,15.4700,4.2
2,320-53-2674,A,Yangon,NaN,FEMALE,Food and beverages,78.29 GHS,3.0,11.7435,246.61,2/5/2019,Ewallet,234.87,4.761905,11.7435,8.2
3,649-25-7201,A,Yangon,Normal,Male,Fashion accessories,86.27 GHS,10.0,43.1350,905.83,"March 15, 2019",Cash,862.70,4.761905,43.1350,5.6
4,975-39-2654,A,Yangon,Normal,NaN,Home and lifestyle,27.31 GHS,2.0,2.7310,57.35,"February 3, 2019",Cash,54.62,4.761905,2.7310,4.3

In [10]:
df.isnull().sum()

invoice_id        0
branch           19
city              0
customer_type    16
gender           13
product_line      0
unit_price        0
quantity          0
tax               0
total            21
date              0
payment           0
cogs              0
gross_margin      0
gross_income      0
rating           17
dtype: int64

In [11]:
df.describe()

,quantity,tax,total,cogs,gross_margin,gross_income,rating
count,205.000000,205.000000,184.000000,205.000000,2.050000e+02,205.000000,188.00000
mean,5.580488,14.856880,304.827174,297.137610,4.761905e+00,14.856880,7.04734
std,3.216015,10.928635,224.501828,218.572708,2.047811e-14,10.928635,1.72885
min,-5.000000,0.819500,17.210000,16.390000,4.761905e+00,0.819500,4.10000
25%,3.000000,5.852500,118.940000,117.050000,4.761905e+00,5.852500,5.60000
50%,6.000000,12.760500,262.780000,255.210000,4.761905e+00,12.760500,6.95000
75%,8.000000,20.601000,429.957500,412.020000,4.761905e+00,20.601000,8.60000
max,10.000000,46.435000,975.130000,928.700000,4.761905e+00,46.435000,10.00000

In [12]:
#before
print("Type before", df['unit_price'].dtype)
print(df['unit_price'].head(3))

Type before object
0    34.75 GHS
1    30.94 GHS
2    78.29 GHS
Name: unit_price, dtype: object

In [13]:
#remove ghs from it
df['unit_price'] = df['unit_price'].str.replace("GHS", "").str.strip()

print(df['unit_price'])

0      34.75
1      30.94
2      78.29
3      86.27
4      27.31
       ...
200    18.37
201    14.16
202    26.07
203    34.75
204    77.93
Name: unit_price, Length: 205, dtype: object

In [14]:
#convert to a proper numbrer
df["unit_price"] = pd.to_numeric(df["unit_price"], errors="coerce")

print("Type after", df['unit_price'].dtype)
print(df['unit_price'].head())

Type after float64
0    34.75
1    30.94
2    78.29
3    86.27
4    27.31
Name: unit_price, dtype: float64

In [15]:
df['date'].head()

0           3/24/2019
1      March 21, 2019
2            2/5/2019
3      March 15, 2019
4    February 3, 2019
Name: date, dtype: object

In [16]:
df['date'] = pd.to_datetime(df['date'], format="mixed")

print("after", df['date'].dtype)
print(df['date'].head(6))

after datetime64[ns]
0   2019-03-24
1   2019-03-21
2   2019-02-05
3   2019-03-15
4   2019-02-03
5   2019-03-09
Name: date, dtype: datetime64[ns]

In [17]:
#extract months and days from the date
df["month"]=df['date'].dt.month
df["day"]=df['date'].dt.day
df["year"]=df["date"].dt.year
df[["date", "month", "year", "day"]].head(5)

        date  month  year  day
0 2019-03-24      3  2019   24
1 2019-03-21      3  2019   21
2 2019-02-05      2  2019    5
3 2019-03-15      3  2019   15
4 2019-02-03      2  2019    3

In [18]:
df.dtypes

invoice_id               object
branch                   object
city                     object
customer_type            object
gender                   object
product_line             object
unit_price              float64
quantity                float64
tax                     float64
total                   float64
date             datetime64[ns]
payment                  object
cogs                    float64
gross_margin            float64
gross_income            float64
rating                  float64
month                     int32
day                       int32
year                      int32
dtype: object

In [19]:
print(df.isnull().sum())

invoice_id        0
branch           19
city              0
customer_type    16
gender           13
product_line      0
unit_price        0
quantity          0
tax               0
total            21
date              0
payment           0
cogs              0
gross_margin      0
gross_income      0
rating           17
month             0
day               0
year              0
dtype: int64

In [20]:
missing_pct = (df.isnull().sum()/len(df)*100).round(1)

print(missing_pct)

invoice_id        0.0
branch            9.3
city              0.0
customer_type     7.8
gender            6.3
product_line      0.0
unit_price        0.0
quantity          0.0
tax               0.0
total            10.2
date              0.0
payment           0.0
cogs              0.0
gross_margin      0.0
gross_income      0.0
rating            8.3
month             0.0
day               0.0
year              0.0
dtype: float64

In [21]:
# filling rating to a complete number
df['rating'] = df['rating'].fillna(df['rating'].mean())

df['total'] = df['total'].fillna(df['total'].mean())

print("Missing in rating", df["rating"].isnull().sum())
print("Missing in total", df["total"].isnull().sum())

Missing in rating 0
Missing in total 0

In [22]:
# filling text
df['branch']= df['branch'].fillna("unknown")
df['customer_type']= df['customer_type'].fillna("unknown")
df['gender']= df['gender'].fillna("unknown")

print("Missing in branch", df["branch"].isnull().sum())
print("Missing in customer_type", df["customer_type"].isnull().sum())
print("Missing in gender", df["gender"].isnull().sum())

Missing in branch 0
Missing in customer_type 0
Missing in gender 0

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   invoice_id     205 non-null    object
 1   branch         205 non-null    object
 2   city           205 non-null    object
 3   customer_type  205 non-null    object
 4   gender         205 non-null    object
 5   product_line   205 non-null    object
 6   unit_price     205 non-null    float64
 7   quantity       205 non-null    float64
 8   tax            205 non-null    float64
 9   total          205 non-null    float64
 10  date           205 non-null    datetime64[ns]
 11  payment        205 non-null    object
 12  cogs           205 non-null    float64
 13  gross_margin   205 non-null    float64
 14  gross_income   205 non-null    float64
 15  rating         205 non-null    float64
 16  month          205 non-null    int32
 17  day            205 non-null    int32
 18  year           205 non-null    int32
dtypes: datetime64[ns](1), float64(8), int32(3), object(7)
memory usage: 28.2+ KB

In [24]:
print("Rows after droping", len(df))

Rows after droping 205

In [25]:
df=df.dropna()

print(df.isnull().sum())

invoice_id       0
branch           0
city             0
customer_type    0
gender           0
product_line     0
unit_price       0
quantity         0
tax              0
total            0
date             0
payment          0
cogs             0
gross_margin     0
gross_income     0
rating           0
month            0
day              0
year             0
dtype: int64

In [26]:
df.head()

,invoice_id,branch,city,customer_type,gender,product_line,unit_price,quantity,tax,total,date,payment,cogs,gross_margin,gross_income,rating,month,day,year
0,658-21-7912,C,Naypyitaw,Member,Male,Sports and travel,34.75,4.0,6.9500,145.950000,2019-03-24,Cash,139.00,4.761905,6.9500,4.8,3,24,2019
1,818-79-7873,A,Yangon,Member,Male,Electronic accessories,30.94,10.0,15.4700,304.827174,2019-03-21,Cash,309.40,4.761905,15.4700,4.2,3,21,2019
2,320-53-2674,A,Yangon,unknown,FEMALE,Food and beverages,78.29,3.0,11.7435,246.610000,2019-02-05,Ewallet,234.87,4.761905,11.7435,8.2,2,5,2019
3,649-25-7201,A,Yangon,Normal,Male,Fashion accessories,86.27,10.0,43.1350,905.830000,2019-03-15,Cash,862.70,4.761905,43.1350,5.6,3,15,2019
4,975-39-2654,A,Yangon,Normal,unknown,Home and lifestyle,27.31,2.0,2.7310,57.350000,2019-02-03,Cash,54.62,4.761905,2.7310,4.3,2,3,2019

In [27]:
df["city"].count()

np.int64(205)

In [28]:
# filtering by one condition
Branch_a = df[df['branch'] == "A"]
print(len(Branch_a))
Branch_a.head()

59

,invoice_id,branch,city,customer_type,gender,product_line,unit_price,quantity,tax,total,date,payment,cogs,gross_margin,gross_income,rating,month,day,year
1,818-79-7873,A,Yangon,Member,Male,Electronic accessories,30.94,10.0,15.4700,304.827174,2019-03-21,Cash,309.40,4.761905,15.4700,4.2,3,21,2019
2,320-53-2674,A,Yangon,unknown,FEMALE,Food and beverages,78.29,3.0,11.7435,246.610000,2019-02-05,Ewallet,234.87,4.761905,11.7435,8.2,2,5,2019
3,649-25-7201,A,Yangon,Normal,Male,Fashion accessories,86.27,10.0,43.1350,905.830000,2019-03-15,Cash,862.70,4.761905,43.1350,5.6,3,15,2019
4,975-39-2654,A,Yangon,Normal,unknown,Home and lifestyle,27.31,2.0,2.7310,57.350000,2019-02-03,Cash,54.62,4.761905,2.7310,4.3,2,3,2019
7,317-93-9179,A,Yangon,Member,Male,Fashion accessories,46.10,2.0,4.6100,96.810000,2019-03-11,Credit card,92.20,4.761905,4.6100,5.3,3,11,2019

In [29]:
# Here i want to get highest sales
highest_sales = df[df['total'] > 400]

print(len(highest_sales))

54

In [30]:
df.head(5)

,invoice_id,branch,city,customer_type,gender,product_line,unit_price,quantity,tax,total,date,payment,cogs,gross_margin,gross_income,rating,month,day,year
0,658-21-7912,C,Naypyitaw,Member,Male,Sports and travel,34.75,4.0,6.9500,145.950000,2019-03-24,Cash,139.00,4.761905,6.9500,4.8,3,24,2019
1,818-79-7873,A,Yangon,Member,Male,Electronic accessories,30.94,10.0,15.4700,304.827174,2019-03-21,Cash,309.40,4.761905,15.4700,4.2,3,21,2019
2,320-53-2674,A,Yangon,unknown,FEMALE,Food and beverages,78.29,3.0,11.7435,246.610000,2019-02-05,Ewallet,234.87,4.761905,11.7435,8.2,2,5,2019
3,649-25-7201,A,Yangon,Normal,Male,Fashion accessories,86.27,10.0,43.1350,905.830000,2019-03-15,Cash,862.70,4.761905,43.1350,5.6,3,15,2019
4,975-39-2654,A,Yangon,Normal,unknown,Home and lifestyle,27.31,2.0,2.7310,57.350000,2019-02-03,Cash,54.62,4.761905,2.7310,4.3,2,3,2019

In [31]:
# filter by two condition
Branch_a_highest_sales = df[(df['branch'] == "A") & (df['total'] > 300)]

print(len(Branch_a_highest_sales))

23

In [32]:
# city highest sales
city_highest_sales = df[(df["city"] == "Yangon") & (df["total"] > 300)]

print(len(city_highest_sales))
city_highest_sales.head(10)

28

,invoice_id,branch,city,customer_type,gender,product_line,unit_price,quantity,tax,total,date,payment,cogs,gross_margin,gross_income,rating,month,day,year
1,818-79-7873,A,Yangon,Member,Male,Electronic accessories,30.94,10.0,15.470,304.827174,2019-03-21,Cash,309.40,4.761905,15.470,4.20000,3,21,2019
3,649-25-7201,A,Yangon,Normal,Male,Fashion accessories,86.27,10.0,43.135,905.830000,2019-03-15,Cash,862.70,4.761905,43.135,5.60000,3,15,2019
19,177-66-2604,A,Yangon,Member,Male,Home and lifestyle,50.38,-2.0,17.633,304.827174,2019-01-28,Ewallet,352.66,4.761905,17.633,5.10000,1,28,2019
26,108-95-5905,A,Yangon,Normal,Female,Electronic accessories,49.44,9.0,22.248,467.210000,2019-03-17,Credit card,444.96,4.761905,22.248,8.20000,3,17,2019
50,872-13-5051,A,Yangon,Normal,Male,Sports and travel,58.55,6.0,17.565,368.860000,2019-03-02,Cash,351.30,4.761905,17.565,7.04734,3,2,2019
55,561-41-8613,A,Yangon,unknown,Female,Health and beauty,49.20,10.0,24.600,516.600000,2019-01-09,Cash,492.00,4.761905,24.600,5.60000,1,9,2019
89,944-71-5835,A,Yangon,Member,Male,Home and lifestyle,88.88,6.0,26.664,559.940000,2019-01-09,Ewallet,533.28,4.761905,26.664,7.20000,1,9,2019
91,698-58-7086,unknown,Yangon,Normal,Male,Fashion accessories,58.29,8.0,23.316,489.640000,2019-03-09,Credit card,466.32,4.761905,23.316,6.20000,3,9,2019
92,164-91-8606,unknown,Yangon,Member,Female,Food and beverages,65.76,9.0,29.592,621.430000,2019-01-21,Credit card,591.84,4.761905,29.592,6.00000,1,21,2019
97,321-39-6383,unknown,Yangon,normal,Male,Electronic accessories,80.83,4.0,16.166,339.490000,2019-01-19,Credit card,323.32,4.761905,16.166,7.04734,1,19,2019

In [33]:
#filter by one condition
customer_type_member = df[df['customer_type'] == "Member"]

print(len(customer_type_member))

90

In [34]:
regular_customers = df[(df['customer_type'] == "Member")  | (df['customer_type'] == "Normal")]

print(len(regular_customers))

175

In [35]:
males_opt_sporst_n_travels = df[(df['gender'] == "Male") & (df['product_line'] == "Sports and travel")]

print(len(males_opt_sporst_n_travels))

22

In [36]:
total_sports_sales = df[df['product_line'] == "Sports and travel"]
print(len(total_sports_sales))

38

In [37]:
#unit_price_highest
unit_price_highest = df[df['quantity'] == -2]

print(len(unit_price_highest))

1

In [38]:
#customer_higher_purchase
customer_higher_purchase = df[df["total"] > 500]
print(len(customer_higher_purchase))

37

In [39]:
# sort by total values

df.sort_values("total", ascending=False).head(5)

,invoice_id,branch,city,customer_type,gender,product_line,unit_price,quantity,tax,total,date,payment,cogs,gross_margin,gross_income,rating,month,day,year
36,619-49-7691,B,Mandalay,Normal,Male,Sports and travel,92.87,10.0,46.4350,975.13,2019-03-10,Cash,928.70,4.761905,46.4350,5.9,3,10,2019
98,987-13-3159,A,Yangon,Member,Female,Electronic accessories,98.88,9.0,44.4960,934.42,2019-01-22,Cash,889.92,4.761905,44.4960,5.5,1,22,2019
3,649-25-7201,A,Yangon,Normal,Male,Fashion accessories,86.27,10.0,43.1350,905.83,2019-03-15,Cash,862.70,4.761905,43.1350,5.6,3,15,2019
94,524-93-2622,B,Mandalay,Normal,unknown,Sports and travel,95.44,9.0,42.9480,901.91,2019-03-05,Credit card,858.96,4.761905,42.9480,6.5,3,5,2019
142,180-65-3956,A,Yangon,Normal,Female,Fashion accessories,93.19,9.0,41.9355,880.65,2019-03-14,Cash,838.71,4.761905,41.9355,5.6,3,14,2019

In [40]:
# sort from lowest sales
df.sort_values("total", ascending=True).head(5)

,invoice_id,branch,city,customer_type,gender,product_line,unit_price,quantity,tax,total,date,payment,cogs,gross_margin,gross_income,rating,month,day,year
16,626-40-5562,A,Yangon,Member,Male,Food and beverages,16.39,1.0,0.8195,17.21,2019-02-03,Cash,16.39,4.761905,0.8195,5.4,2,3,2019
52,506-35-2245,C,Naypyitaw,Member,Male,Fashion accessories,19.73,1.0,0.9865,20.72,2019-03-13,Credit card,19.73,4.761905,0.9865,9.6,3,13,2019
93,340-78-3222,C,Naypyitaw,Normal,Female,Food and beverages,22.58,1.0,1.1290,23.71,2019-01-04,Ewallet,22.58,4.761905,1.1290,5.8,1,4,2019
114,514-91-7843,A,Yangon,Normal,Male,Health and beauty,11.69,2.0,1.1690,24.55,2019-02-19,Credit card,23.38,4.761905,1.1690,9.2,2,19,2019
81,864-21-8110,unknown,Mandalay,Normal,Female,Home and lifestyle,13.23,2.0,1.3230,27.78,2019-02-08,Credit card,26.46,4.761905,1.3230,5.4,2,8,2019

In [41]:
# sort by multiple columns
df.sort_values(["branch", "total"], ascending=[True, False]).head(10)

,invoice_id,branch,city,customer_type,gender,product_line,unit_price,quantity,tax,total,date,payment,cogs,gross_margin,gross_income,rating,month,day,year
98,987-13-3159,A,Yangon,Member,Female,Electronic accessories,98.88,9.0,44.4960,934.42,2019-01-22,Cash,889.92,4.761905,44.4960,5.5,1,22,2019
3,649-25-7201,A,Yangon,Normal,Male,Fashion accessories,86.27,10.0,43.1350,905.83,2019-03-15,Cash,862.70,4.761905,43.1350,5.6,3,15,2019
142,180-65-3956,A,Yangon,Normal,Female,Fashion accessories,93.19,9.0,41.9355,880.65,2019-03-14,Cash,838.71,4.761905,41.9355,5.6,3,14,2019
190,488-39-5055,A,Yangon,Member,Male,Food and beverages,98.06,8.0,39.2240,823.70,2019-02-18,Credit card,784.48,4.761905,39.2240,8.0,2,18,2019
149,455-18-9882,A,Yangon,Member,unknown,Electronic accessories,90.88,8.0,36.3520,763.39,2019-02-22,Credit card,727.04,4.761905,36.3520,10.0,2,22,2019
177,396-14-1151,A,Yangon,Normal,MALE,Food and beverages,99.75,7.0,34.9125,733.16,2019-03-28,Cash,698.25,4.761905,34.9125,8.7,3,28,2019
89,944-71-5835,A,Yangon,Member,Male,Home and lifestyle,88.88,6.0,26.6640,559.94,2019-01-09,Ewallet,533.28,4.761905,26.6640,7.2,1,9,2019
165,426-30-7438,A,Yangon,Normal,FEMALE,Home and lifestyle,51.13,10.0,25.5650,536.87,2019-02-20,Cash,511.30,4.761905,25.5650,9.4,2,20,2019
55,561-41-8613,A,Yangon,unknown,Female,Health and beauty,49.20,10.0,24.6000,516.60,2019-01-09,Cash,492.00,4.761905,24.6000,5.6,1,9,2019
26,108-95-5905,A,Yangon,Normal,Female,Electronic accessories,49.44,9.0,22.2480,467.21,2019-03-17,Credit card,444.96,4.761905,22.2480,8.2,3,17,2019

Groupby and aggregation

In [42]:
# total revenue per branch
df.groupby("branch")["total"].sum().round(2)

branch
A          16944.54
B          23231.36
C          15723.24
unknown     6590.43
Name: total, dtype: float64

In [43]:
# average rating per branch
df.groupby("branch")["rating"].mean().round(2)

branch
A          7.13
B          7.03
C          7.21
unknown    6.39
Name: rating, dtype: float64

In [44]:
# number of transaction per product line
df.groupby("product_line")["invoice_id"].count()

product_line
Electronic accessories    34
Fashion accessories       31
Food and beverages        34
Health and beauty         32
Home and lifestyle        36
Sports and travel         38
Name: invoice_id, dtype: int64

In [45]:
# count, total and average per product_line
df.groupby("product_line")["total"].agg(["count", "sum", "mean"]).round(2)

                        count       sum    mean
product_line
Electronic accessories     34  10878.57  319.96
Fashion accessories        31  10146.69  327.31
Food and beverages         34   9704.05  285.41
Health and beauty          32   8675.31  271.10
Home and lifestyle         36  10491.82  291.44
Sports and travel          38  12593.13  331.40

In [46]:
df.head(5)

,invoice_id,branch,city,customer_type,gender,product_line,unit_price,quantity,tax,total,date,payment,cogs,gross_margin,gross_income,rating,month,day,year
0,658-21-7912,C,Naypyitaw,Member,Male,Sports and travel,34.75,4.0,6.9500,145.950000,2019-03-24,Cash,139.00,4.761905,6.9500,4.8,3,24,2019
1,818-79-7873,A,Yangon,Member,Male,Electronic accessories,30.94,10.0,15.4700,304.827174,2019-03-21,Cash,309.40,4.761905,15.4700,4.2,3,21,2019
2,320-53-2674,A,Yangon,unknown,FEMALE,Food and beverages,78.29,3.0,11.7435,246.610000,2019-02-05,Ewallet,234.87,4.761905,11.7435,8.2,2,5,2019
3,649-25-7201,A,Yangon,Normal,Male,Fashion accessories,86.27,10.0,43.1350,905.830000,2019-03-15,Cash,862.70,4.761905,43.1350,5.6,3,15,2019
4,975-39-2654,A,Yangon,Normal,unknown,Home and lifestyle,27.31,2.0,2.7310,57.350000,2019-02-03,Cash,54.62,4.761905,2.7310,4.3,2,3,2019

In [47]:
# group by two columns
df.groupby(["branch", "customer_type"])["total"].sum().round(2)

branch   customer_type
A        Member            8375.90
         Normal            6147.44
         member            1059.45
         unknown           1361.75
B        Member            8728.14
         Normal           11452.42
         member              39.57
         normal             388.56
         unknown           2622.67
C        Member            6848.18
         Normal            5962.03
         member            1017.24
         normal             264.98
         unknown           1630.80
unknown  Member            3059.05
         Normal            1974.60
         normal            1556.78
Name: total, dtype: float64

In [48]:
df["customer_type"] = df["customer_type"].str.capitalize()
df["customer_type"].unique()

array(['Member', 'Unknown', 'Normal'], dtype=object)

Ranking

In [49]:
# rank product line by total revenue
product_revenue=(df.groupby("product_line")["total"].sum().round().reset_index().rename(columns={"total": "total_revenue"}))

product_revenue.sort_values("total_revenue", ascending=False)
print(product_revenue)

             product_line  total_revenue
0  Electronic accessories        10879.0
1     Fashion accessories        10147.0
2      Food and beverages         9704.0
3       Health and beauty         8675.0
4      Home and lifestyle        10492.0
5       Sports and travel        12593.0

In [50]:
product_revenue = (df.groupby("product_line")["total"].sum().round(2))

product_rank = product_revenue.rank(ascending=False)

print(product_rank)

product_line
Electronic accessories    2.0
Fashion accessories       4.0
Food and beverages        5.0
Health and beauty         6.0
Home and lifestyle        3.0
Sports and travel         1.0
Name: total, dtype: float64

Which product has the highet revenue

In [51]:
highest_revenue_product = (
    df.groupby("product_line")["total"].sum()
    .round(2)
    .reset_index()
    .rename(columns={"total": "total_revenue"})
)

highest_revenue_product = highest_revenue_product.sort_values(
    by="total_revenue", ascending=False
)

print(highest_revenue_product)

             product_line  total_revenue
5       Sports and travel       12593.13
0  Electronic accessories       10878.57
4      Home and lifestyle       10491.82
1     Fashion accessories       10146.69
2      Food and beverages        9704.05
3       Health and beauty        8675.31

Average revenue on which customer_type

In [52]:
# total + mean + sort
customer_average_revenue = (df.groupby("customer_type")["total"].mean().round(2)
                            .reset_index()
                            .rename(columns={"total": "average_revenue"}))

customer_average_revenue = customer_average_revenue.sort_values(by="average_revenue", ascending=False)

print(customer_average_revenue)

  customer_type  average_revenue
2       Unknown           350.95
1        Normal           301.60
0        Member           300.28